### ISSUE TITLE
Terser 4 meta-issue

### ISSUE THREAD

**Issue by fabiosantoscode** [terser-js/terser#301]
This issue is meant to outline which changes are going to come in Terser 4.0. It didn't come out this weekend as expected, since life said no.

## Breaking changes that have to be completed for Terser 4

 - [ ] Terser 4 is no longer going to have beautify functionality. `lib/output.js` code will remain the same but will purposefully crash when `beautify=true` is used.
 - [ ] Deprecation of some output options meant for beautify.
 - [ ] Setting `safari10` to true by default for all stages.
 - [x] Dropping node 4 support

Until all of these are completed, there will be no new Terser version.

**Comment by fabiosantoscode** [comment]
I can't complete all these changes for Terser 4 so they need to wait for a new version.

**Comment by cekvenich** [comment]
So 4.0 is released with all of these or some of these?
